### ISSUE TITLE
This repo should be renamed to "xnim"

### ISSUE THREAD

**Issue by sjakobi** [exercism/xnim#10]
With version 0.10.2 the Nimrod language [was renamed to Nim](http://nim-lang.org/news.html).

Can this repo also be renamed to xnim, @kytrinyx? It seems like only the owner can change the repo settings, and that's you…

[Github Docs on this topic](https://help.github.com/articles/renaming-a-repository/)

**Comment by sjakobi** [comment]
BTW I'm sorry that there haven't been any updates here. I've been super occupied with college and work and other languages…

I'll probably try to find a new maintainer via http://www.reddit.com/r/nim or the language forums, if that's ok? It shouldn't be too hard as the language is getting a lot of coverage on HN and r/programming these days.

**Comment by kytrinyx** [comment]
I've renamed the repo. Feel free to recruit other maintainers. Always happy to have more people involved!

**Comment by sjakobi** [comment]
Thanks, Katrina!
